---
title: "Installing QGIS"
author: "Nick Bearman"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

We will be setting up QGIS. Follow the instructions below, depending on your operating system.

##Windows 

- Open a web browser and go to http://www.qgis.org.  
- Click **Download Now**.  
- Download the latest version of **QGIS Standalone Installer** (currently 3.4). *Select the 64 bit version, unless you have a very old computer, or know that you need the 32 bit version*.  
- Run through the program installation process.  

##OSX

- Open a web browser and go to http://www.qgis.org.  
- Click **Download Now**.  
- Under **Download for Mac OS X** click **QGIS macOS Installer Version 3.4.0**.  
- Open the disk image file you just downloaded. There are various different components to install, and they need to be installed in order.  
- Open `1 Install Python 3.rft` and read the information. Download the latest 3.6.x Python installation from https://www.python.org/downloads/mac-osx/ (currently 3.6.6). **Do NOT install Python 3.7.0 or higher - currently this doesn't work with QGIS.**
- Continue with `2 Install GDAL Complete.pkg` by right-clicking on the file and choosing `Open` *(double clicking will probably not work)*.  
- Follow through the installation wizard, and then repeat for `3 Install QGIS 3.pkg`.  

##Linux/Ubuntu

- Open a web browser and go to http://www.qgis.org.  
- Click **Download Now**.  
- Expand the **Download for Linux** option.  
- Follow the instructions for the appropiate Linux distribution.  
<!-- add more to this section -->

You are good to go!

*This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/deed.en. The latest version of this is available from https://github.com/nickbearman/installing-software/qgis.Rmd. This version was created on `r format(Sys.time(), '%d %B %Y')`.*
